### ISSUE TITLE
Latest version in docs is out of date

### ISSUE THREAD

**Issue by masonoise** [websudos/util#18]
Just a heads-up that your README file says "The latest available version of the util library is val UtilVersion = 0.6.0" but that's incorrect -- that version is no longer there, so I had to chase down a good version like 0.6.7 in order for the resolver to be happy.

**Comment by alexflav23** [comment]
@masonoise Thank you for reporting this, it will be fixed very shortly and the docs will be updated.

**Comment by alexflav23** [comment]
@masonoise Version 0.7.0 was just released to Maven Central, it will be there and stay there. It may take up to 2 hours for it to appear. There are also several new features in 0.7.0, better described in the pull request.
